//
// HubAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class HubAPI: APIBase {
    /**
     run adb  command
     
     - parameter device: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func adbCommand(device device: Device5? = nil, completion: ((data: InlineResponse2001?, error: ErrorType?) -> Void)) {
        adbCommandWithRequestBuilder(device: device).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     run adb  command
     - POST /device/command
     - examples: [{contentType=application/json, example={
  "msg" : "aeiou",
  "status" : true
}}]
     
     - parameter device: (body)  (optional)

     - returns: RequestBuilder<InlineResponse2001> 
     */
    public class func adbCommandWithRequestBuilder(device device: Device5? = nil) -> RequestBuilder<InlineResponse2001> {
        let path = "/device/command"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = device?.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<InlineResponse2001>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     run adb shell command
     
     - parameter device: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func deviceShell(device device: Device4? = nil, completion: ((data: InlineResponse200?, error: ErrorType?) -> Void)) {
        deviceShellWithRequestBuilder(device: device).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     run adb shell command
     - POST /device/shell
     - examples: [{contentType=application/json, example={
  "msg" : "aeiou",
  "status" : true
}}]
     
     - parameter device: (body)  (optional)

     - returns: RequestBuilder<InlineResponse200> 
     */
    public class func deviceShellWithRequestBuilder(device device: Device4? = nil) -> RequestBuilder<InlineResponse200> {
        let path = "/device/shell"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = device?.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<InlineResponse200>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     list all attached devices to RobusTest
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func devicesList(completion: ((data: HubDevices?, error: ErrorType?) -> Void)) {
        devicesListWithRequestBuilder().execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     list all attached devices to RobusTest
     - GET /devices
     - examples: [{contentType=application/json, example={ }}]

     - returns: RequestBuilder<HubDevices> 
     */
    public class func devicesListWithRequestBuilder() -> RequestBuilder<HubDevices> {
        let path = "/devices"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<HubDevices>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     free device
     
     - parameter device: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func freeDevice(device device: Device1? = nil, completion: ((data: Device?, error: ErrorType?) -> Void)) {
        freeDeviceWithRequestBuilder(device: device).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     free device
     - DELETE /device
     - examples: [{contentType=application/json, example={
  "os" : "aeiou",
  "reserveKey" : "aeiou",
  "serial" : "aeiou",
  "session" : "aeiou",
  "name" : "aeiou",
  "_id" : "aeiou",
  "version" : "aeiou"
}}]
     
     - parameter device: (body)  (optional)

     - returns: RequestBuilder<Device> 
     */
    public class func freeDeviceWithRequestBuilder(device device: Device1? = nil) -> RequestBuilder<Device> {
        let path = "/device"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = device?.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Device>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     get free device based on given parameters
     
     - parameter device: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getFreeDevice(device device: Device? = nil, completion: ((data: Device?, error: ErrorType?) -> Void)) {
        getFreeDeviceWithRequestBuilder(device: device).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     get free device based on given parameters
     - PUT /device
     - examples: [{contentType=application/json, example={
  "os" : "aeiou",
  "reserveKey" : "aeiou",
  "serial" : "aeiou",
  "session" : "aeiou",
  "name" : "aeiou",
  "_id" : "aeiou",
  "version" : "aeiou"
}}]
     
     - parameter device: (body)  (optional)

     - returns: RequestBuilder<Device> 
     */
    public class func getFreeDeviceWithRequestBuilder(device device: Device? = nil) -> RequestBuilder<Device> {
        let path = "/device"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = device?.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Device>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     get screenshot from device
     
     - parameter device: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getScreenshot(device device: Device2? = nil, completion: ((data: NSURL?, error: ErrorType?) -> Void)) {
        getScreenshotWithRequestBuilder(device: device).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     get screenshot from device
     - POST /device/screenshot
     - examples: [{contentType=application/json, example=""}]
     
     - parameter device: (body)  (optional)

     - returns: RequestBuilder<NSURL> 
     */
    public class func getScreenshotWithRequestBuilder(device device: Device2? = nil) -> RequestBuilder<NSURL> {
        let path = "/device/screenshot"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = device?.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<NSURL>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     unrevrse the device
     
     - parameter device: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func unreserveDevice(device device: Device3? = nil, completion: ((data: Device?, error: ErrorType?) -> Void)) {
        unreserveDeviceWithRequestBuilder(device: device).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     unrevrse the device
     - DELETE /device/screenshot
     - examples: [{contentType=application/json, example={
  "os" : "aeiou",
  "reserveKey" : "aeiou",
  "serial" : "aeiou",
  "session" : "aeiou",
  "name" : "aeiou",
  "_id" : "aeiou",
  "version" : "aeiou"
}}]
     
     - parameter device: (body)  (optional)

     - returns: RequestBuilder<Device> 
     */
    public class func unreserveDeviceWithRequestBuilder(device device: Device3? = nil) -> RequestBuilder<Device> {
        let path = "/device/screenshot"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = device?.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Device>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
