swagger-codegen generate -i swagger.json  -l python -o client/python
swagger-codegen generate -i swagger.json  -l java -o client/java
swagger-codegen generate -i swagger.json  -l ruby -o client/ruby
swagger-codegen generate -i swagger.json  -l go -o client/go
swagger-codegen generate -i swagger.json  -l php -o client/php
swagger-codegen generate -i swagger.json  -l perl -o client/perl
swagger-codegen generate -i swagger.json  -l javascript -o client/javascript
swagger-codegen generate -i swagger.json  -l csharp -o client/csharp
swagger-codegen generate -i swagger.json  -l swift -o client/swift
swagger-codegen generate -i swagger.json  -l html -o doc
