swagger: '3.0'
title: RobusTest Api documentation 
description: RobusTest Api documentation
version: 1.0.1


# host: mobile.robustest.com:8085
# schemes:
#   - http
#   - https
produces:
  - application/json
# basePath: /v2
paths:
  /admin/v3/bug/config/jira:
    post:
      summary: create a jira config
      consumes:
        - application/json
      produces:
        - application/json
      description: create a jira config
      operationId: jira config
      parameters:
        - description: jira config payload
        - name: body
          in: body
          required: true
          schema:
              $ref: '#/definitions/JiraConfigPayload'
      responses:
        '200':    # status code
          description: A JSON array of jira project names
          schema: 
            type: array
            items: 
              type: string
  /admin/v3/bug/config/jira/configs:
    get:
      summary : get all jira config 
      produces:
        -application/json
      description: get all jira config
      operationId: jira config
      responses:
        '200':    # status code
          description: get list of jira config
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#/definitions/JiraConfig'


definitions:
  JiraConfigPayload:
    type : object
    required: 
      - "url"
      - "name"
      - "user"
      - "password"
    properties: 
      url: 
        type: "string"
      name: 
        type: "string"
      user: 
        type: "string"
      password: 
        type: "string"
  JiraConfig:
    type : object
    properties: 
      _id: 
        type: "string"
      source: 
        type: "string"
      type: 
        type: "string"
      url: 
        type: "string"
      name: 
        type: "string"
      user: 
        type: "string"
      password: 
        type: "string"
      createdBy: 
        type: "string"
      updated: 
        type: "string"
      created: 
        type: "string"
  JiraProject:
    type: object
    properties: 
      _id: 
        type: "string"
      source: 
        type: "string"
      key: 
        type: "string"
      id: 
        type: "string"
      name: 
        type: "string"
      desc: 
        type: "string"
      users: 
        type: "array"
        items: 
          type: "object"
          properties: 
            key: 
              type: "string"
            name: 
              type: "string"
            email: 
              type: "string"
            avatarUrl: 
              type: "string"
            displayName: 
              type: "string"
      type: 
        type: "string"
      component: 
        type: "array"
        items: 
          type: "object"
          properties: 
            id: 
              type: "string"
            name: 
              type: "string"
      updated: 
        type: "string"
      created: 
        type: "string"







# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /Izinga/Hub/1.0.0
schemes:
 - https
 - http
