=begin comment

RobusTest Hub

RobusTest Hub Api [http://mobile.robustest.com:8085 

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package WWW::SwaggerClient::HubApi;

require 5.6.0;
use strict;
use warnings;
use utf8; 
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::SwaggerClient::ApiClient;
use WWW::SwaggerClient::Configuration;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class   = shift;
    my (%self) = (
        'api_client' => WWW::SwaggerClient::ApiClient->instance,
        @_
    );

    #my $self = {
    #    #api_client => $options->{api_client}
    #    api_client => $default_api_client
    #}; 

    bless \%self, $class;

}


#
# device_command_post
#
# run adb  command
# 
# @param Device5 $device  (optional)
{
    my $params = {
    'device' => {
        data_type => 'Device5',
        description => '',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'device_command_post' } = { 
    	summary => 'run adb  command',
        params => $params,
        returns => 'InlineResponse2001',
        };
}
# @return InlineResponse2001
#
sub device_command_post {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/device/command';
    $_resource_path =~ s/{format}/json/; # default format to json

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'device'}) {
        $_body_data = $args{'device'};
    }

    # authentication setting, if any
    my $auth_settings = [qw()];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('InlineResponse2001', $response);
    return $_response_object;
}

#
# device_delete
#
# free device
# 
# @param Device1 $device  (optional)
{
    my $params = {
    'device' => {
        data_type => 'Device1',
        description => '',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'device_delete' } = { 
    	summary => 'free device',
        params => $params,
        returns => 'Device',
        };
}
# @return Device
#
sub device_delete {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/device';
    $_resource_path =~ s/{format}/json/; # default format to json

    my $_method = 'DELETE';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'device'}) {
        $_body_data = $args{'device'};
    }

    # authentication setting, if any
    my $auth_settings = [qw()];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('Device', $response);
    return $_response_object;
}

#
# device_put
#
# get free device based on given parameters
# 
# @param Device $device  (optional)
{
    my $params = {
    'device' => {
        data_type => 'Device',
        description => '',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'device_put' } = { 
    	summary => 'get free device based on given parameters',
        params => $params,
        returns => 'Device',
        };
}
# @return Device
#
sub device_put {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/device';
    $_resource_path =~ s/{format}/json/; # default format to json

    my $_method = 'PUT';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'device'}) {
        $_body_data = $args{'device'};
    }

    # authentication setting, if any
    my $auth_settings = [qw()];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('Device', $response);
    return $_response_object;
}

#
# device_reverse_delete
#
# unrevrse the device
# 
# @param Device3 $device  (optional)
{
    my $params = {
    'device' => {
        data_type => 'Device3',
        description => '',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'device_reverse_delete' } = { 
    	summary => 'unrevrse the device',
        params => $params,
        returns => 'Device',
        };
}
# @return Device
#
sub device_reverse_delete {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/device/reverse';
    $_resource_path =~ s/{format}/json/; # default format to json

    my $_method = 'DELETE';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'device'}) {
        $_body_data = $args{'device'};
    }

    # authentication setting, if any
    my $auth_settings = [qw()];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('Device', $response);
    return $_response_object;
}

#
# device_reverse_put
#
# reverse a device
# 
# @param Device2 $device  (optional)
{
    my $params = {
    'device' => {
        data_type => 'Device2',
        description => '',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'device_reverse_put' } = { 
    	summary => 'reverse a device',
        params => $params,
        returns => 'Device',
        };
}
# @return Device
#
sub device_reverse_put {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/device/reverse';
    $_resource_path =~ s/{format}/json/; # default format to json

    my $_method = 'PUT';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'device'}) {
        $_body_data = $args{'device'};
    }

    # authentication setting, if any
    my $auth_settings = [qw()];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('Device', $response);
    return $_response_object;
}

#
# device_shell_post
#
# run adb shell command
# 
# @param Device4 $device  (optional)
{
    my $params = {
    'device' => {
        data_type => 'Device4',
        description => '',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'device_shell_post' } = { 
    	summary => 'run adb shell command',
        params => $params,
        returns => 'InlineResponse200',
        };
}
# @return InlineResponse200
#
sub device_shell_post {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/device/shell';
    $_resource_path =~ s/{format}/json/; # default format to json

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'device'}) {
        $_body_data = $args{'device'};
    }

    # authentication setting, if any
    my $auth_settings = [qw()];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('InlineResponse200', $response);
    return $_response_object;
}

#
# devices
#
# list all attached devices to RobusTest
# 
{
    my $params = {
    };
    __PACKAGE__->method_documentation->{ 'devices' } = { 
    	summary => 'list all attached devices to RobusTest',
        params => $params,
        returns => 'HubDevices',
        };
}
# @return HubDevices
#
sub devices {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/devices';
    $_resource_path =~ s/{format}/json/; # default format to json

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw()];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('HubDevices', $response);
    return $_response_object;
}

1;
