/*
 * RobusTest Hub
 *
 * RobusTest Hub Api [http://enterprice.robustest.com:8085 
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Device5 struct {

	Id string `json:"_id"`

	Command string `json:"command"`
}
