/* 
 * RobusTest Hub
 *
 * RobusTest Hub Api [http://mobile.robustest.com:8085 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Device struct {

	// device id
	Id string `json:"_id,omitempty"`

	DeviceName string `json:"deviceName,omitempty"`

	PlatformVersion string `json:"platformVersion,omitempty"`

	ReverseKey string `json:"reverseKey,omitempty"`
}
