/*
 * RobusTest Api
 *
 * RobusTest Apis
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type JiraConfig struct {

	Id string `json:"_id,omitempty"`

	Source string `json:"source,omitempty"`

	Type_ string `json:"type,omitempty"`

	Url string `json:"url,omitempty"`

	Name string `json:"name,omitempty"`

	User string `json:"user,omitempty"`

	Password string `json:"password,omitempty"`

	CreatedBy string `json:"createdBy,omitempty"`

	Updated string `json:"updated,omitempty"`

	Created string `json:"created,omitempty"`
}
