/*
 * RobusTest Api
 *
 * RobusTest Apis
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type JiraIssuePayload struct {

	ProjectKey string `json:"projectKey"`

	AssingeeName string `json:"assingeeName"`

	AssingeeKey string `json:"assingeeKey"`

	ReporterName string `json:"reporterName"`

	ReporterKey string `json:"reporterKey"`

	Description string `json:"description"`

	Summary string `json:"summary"`

	Type_ string `json:"type"`

	Attachements []JiraIssuePayloadAttachements `json:"attachements"`
}
