/*
 * RobusTest Api
 *
 * RobusTest Apis
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Project struct {

	Id string `json:"_id,omitempty"`

	Name string `json:"name,omitempty"`

	Org string `json:"org,omitempty"`

	Os string `json:"os,omitempty"`

	Icon64 string `json:"icon64,omitempty"`

	Type_ string `json:"type,omitempty"`

	Url string `json:"url,omitempty"`

	BugProject string `json:"bugProject,omitempty"`

	Admin []string `json:"admin,omitempty"`

	Users []string `json:"users,omitempty"`

	TestC float32 `json:"test_c,omitempty"`

	Active bool `json:"active,omitempty"`

	IsUniversal bool `json:"is_universal,omitempty"`

	Last string `json:"last,omitempty"`

	Created string `json:"created,omitempty"`

	Updated string `json:"updated,omitempty"`

	UpdateBy string `json:"update_by,omitempty"`

	CreatedBy string `json:"created_by,omitempty"`
}
