/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Testsuite struct {

	// Test suite ID
	Id string `json:"_id,omitempty"`

	// Test suite  Name
	Name string `json:"name,omitempty"`

	// Test suite  description
	Desc string `json:"desc,omitempty"`

	// Test suite  project id
	Project string `json:"project,omitempty"`

	// User who created test suite
	CreatedBy string `json:"createdBy,omitempty"`

	// User who uodated test suite
	UpdatedBy string `json:"updatedBy,omitempty"`
}
