=begin
#RobusTest Api

#RobusTest Apis

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/device_status'
require 'swagger_client/models/jira_config'
require 'swagger_client/models/jira_config_payload'
require 'swagger_client/models/jira_issue_payload'
require 'swagger_client/models/jira_issue_payload_attachements'
require 'swagger_client/models/jira_issue_response'
require 'swagger_client/models/jira_project'
require 'swagger_client/models/jira_project_component'
require 'swagger_client/models/jira_project_users'
require 'swagger_client/models/project'
require 'swagger_client/models/project_update_payload'

# APIs
require 'swagger_client/api/default_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
