# coding: utf-8

"""
    RobusTest Hub

    RobusTest Hub Api [http://mobile.robustest.com:8085 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import sys
from setuptools import setup, find_packages

NAME = "swagger_client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="RobusTest Hub",
    author_email="",
    url="",
    keywords=["Swagger", "RobusTest Hub"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    RobusTest Hub Api [http://mobile.robustest.com:8085 
    """
)
