/* 
 * RobusTest Hub
 *
 * RobusTest Hub Api [http://mobile.robustest.com:8085 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Device1
    /// </summary>
    [DataContract]
    public partial class Device1 :  IEquatable<Device1>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Device1" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Device1() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Device1" /> class.
        /// </summary>
        /// <param name="Device">device id (required).</param>
        public Device1(string Device = default(string))
        {
            // to ensure "Device" is required (not null)
            if (Device == null)
            {
                throw new InvalidDataException("Device is a required property for Device1 and cannot be null");
            }
            else
            {
                this.Device = Device;
            }
        }
        
        /// <summary>
        /// device id
        /// </summary>
        /// <value>device id</value>
        [DataMember(Name="device", EmitDefaultValue=false)]
        public string Device { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Device1 {\n");
            sb.Append("  Device: ").Append(Device).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as Device1);
        }

        /// <summary>
        /// Returns true if Device1 instances are equal
        /// </summary>
        /// <param name="other">Instance of Device1 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Device1 other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Device == other.Device ||
                    this.Device != null &&
                    this.Device.Equals(other.Device)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Device != null)
                    hash = hash * 59 + this.Device.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
