=begin
#RobusTest Hub

#RobusTest Hub Api [http://mobile.robustest.com:8085 

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::HubDevices
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'HubDevices' do
  before do
    # run before each test
    @instance = SwaggerClient::HubDevices.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of HubDevices' do
    it 'should create an instact of HubDevices' do
      expect(@instance).to be_instance_of(SwaggerClient::HubDevices)
    end
  end
end

