/* 
 * RobusTest Hub
 *
 * RobusTest Hub Api [http://mobile.robustest.com:8085 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Device5
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Device5Tests
    {
        // TODO uncomment below to declare an instance variable for Device5
        //private Device5 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Device5
            //instance = new Device5();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Device5
        /// </summary>
        [Test]
        public void Device5InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Device5
            //Assert.IsInstanceOfType<Device5> (instance, "variable 'instance' is a Device5");
        }

        /// <summary>
        /// Test the property 'Device'
        /// </summary>
        [Test]
        public void DeviceTest()
        {
            // TODO unit test for the property 'Device'
        }
        /// <summary>
        /// Test the property 'Command'
        /// </summary>
        [Test]
        public void CommandTest()
        {
            // TODO unit test for the property 'Command'
        }

    }

}
