/* 
 * 
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Testsuite
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TestsuiteTests
    {
        // TODO uncomment below to declare an instance variable for Testsuite
        //private Testsuite instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Testsuite
            //instance = new Testsuite();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Testsuite
        /// </summary>
        [Test]
        public void TestsuiteInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Testsuite
            //Assert.IsInstanceOfType<Testsuite> (instance, "variable 'instance' is a Testsuite");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Desc'
        /// </summary>
        [Test]
        public void DescTest()
        {
            // TODO unit test for the property 'Desc'
        }
        /// <summary>
        /// Test the property 'Project'
        /// </summary>
        [Test]
        public void ProjectTest()
        {
            // TODO unit test for the property 'Project'
        }
        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Test]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }
        /// <summary>
        /// Test the property 'UpdatedBy'
        /// </summary>
        [Test]
        public void UpdatedByTest()
        {
            // TODO unit test for the property 'UpdatedBy'
        }

    }

}
