/**
 * RobusTest Api
 * RobusTest Apis
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.RobusTestApi) {
      root.RobusTestApi = {};
    }
    root.RobusTestApi.ProjectUpdatePayload = factory(root.RobusTestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ProjectUpdatePayload model module.
   * @module model/ProjectUpdatePayload
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ProjectUpdatePayload</code>.
   * @alias module:model/ProjectUpdatePayload
   * @class
   * @param active {Boolean} 
   * @param bugProject {String} 
   * @param users {Array.<String>} 
   * @param admin {Array.<String>} 
   */
  var exports = function(active, bugProject, users, admin) {
    var _this = this;

    _this['active'] = active;
    _this['bugProject'] = bugProject;
    _this['users'] = users;
    _this['admin'] = admin;
  };

  /**
   * Constructs a <code>ProjectUpdatePayload</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProjectUpdatePayload} obj Optional instance to populate.
   * @return {module:model/ProjectUpdatePayload} The populated <code>ProjectUpdatePayload</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('active')) {
        obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
      }
      if (data.hasOwnProperty('bugProject')) {
        obj['bugProject'] = ApiClient.convertToType(data['bugProject'], 'String');
      }
      if (data.hasOwnProperty('users')) {
        obj['users'] = ApiClient.convertToType(data['users'], ['String']);
      }
      if (data.hasOwnProperty('admin')) {
        obj['admin'] = ApiClient.convertToType(data['admin'], ['String']);
      }
    }
    return obj;
  }

  /**
   * @member {Boolean} active
   */
  exports.prototype['active'] = undefined;
  /**
   * @member {String} bugProject
   */
  exports.prototype['bugProject'] = undefined;
  /**
   * @member {Array.<String>} users
   */
  exports.prototype['users'] = undefined;
  /**
   * @member {Array.<String>} admin
   */
  exports.prototype['admin'] = undefined;



  return exports;
}));


