# coding: utf-8

"""
    RobusTest Hub

    RobusTest Hub Api [http://mobile.robustest.com:8085 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.device_2 import Device2


class TestDevice2(unittest.TestCase):
    """ Device2 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDevice2(self):
        """
        Test Device2
        """
        model = swagger_client.models.device_2.Device2()


if __name__ == '__main__':
    unittest.main()
