# coding: utf-8

"""
    RobusTest Api

    RobusTest Apis  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.jira_project_component import JiraProjectComponent  # noqa: E501
from swagger_client.rest import ApiException


class TestJiraProjectComponent(unittest.TestCase):
    """JiraProjectComponent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJiraProjectComponent(self):
        """Test JiraProjectComponent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.jira_project_component.JiraProjectComponent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
