# coding: utf-8

"""
    RobusTest Api

    RobusTest Apis  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_bug(self):
        """Test case for bug

        get list for all supported bug trakers  # noqa: E501
        """
        pass

    def test_jira(self):
        """Test case for jira

        get all jira config  # noqa: E501
        """
        pass

    def test_jira_0(self):
        """Test case for jira_0

        get all jira project  # noqa: E501
        """
        pass

    def test_jira_1(self):
        """Test case for jira_1

        get all jira project for given config  # noqa: E501
        """
        pass

    def test_jira_2(self):
        """Test case for jira_2

        get a jira project  details  # noqa: E501
        """
        pass

    def test_jira_config(self):
        """Test case for jira_config

        create a jira config  # noqa: E501
        """
        pass

    def test_jira_config_0(self):
        """Test case for jira_config_0

        update a jira config  # noqa: E501
        """
        pass

    def test_jira_config_1(self):
        """Test case for jira_config_1

        update all projects for a jira config  # noqa: E501
        """
        pass

    def test_jira_issue(self):
        """Test case for jira_issue

        create a jira issue  # noqa: E501
        """
        pass

    def test_project(self):
        """Test case for project

        Update Project  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
