# coding: utf-8

"""
    RobusTest Api

    RobusTest Apis  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.jira_issue_payload_attachements import JiraIssuePayloadAttachements  # noqa: E501
from swagger_client.rest import ApiException


class TestJiraIssuePayloadAttachements(unittest.TestCase):
    """JiraIssuePayloadAttachements unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJiraIssuePayloadAttachements(self):
        """Test JiraIssuePayloadAttachements"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.jira_issue_payload_attachements.JiraIssuePayloadAttachements()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
