/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Testsuite;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TestsuiteApi
 */
@Ignore
public class TestsuiteApiTest {

    private final TestsuiteApi api = new TestsuiteApi();

    
    /**
     * get all test suite for project
     *
     * return all test suite for given project
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void testSuitesForProjectTest() throws ApiException {
        String projectID = null;
        Testsuite response = api.testSuitesForProject(projectID);

        // TODO: test validations
    }
    
}
