/*
 * RobusTest Hub
 * RobusTest Hub Api [http://enterprice.robustest.com:8085 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Device
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-15T13:04:37.852+05:30")
public class Device {
  @SerializedName("_id")
  private String id = null;

  @SerializedName("deviceName")
  private String deviceName = null;

  @SerializedName("platformVersion")
  private String platformVersion = null;

  @SerializedName("reserveKey")
  private String reserveKey = null;

  public Device id(String id) {
    this.id = id;
    return this;
  }

   /**
   * device id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "device id")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Device deviceName(String deviceName) {
    this.deviceName = deviceName;
    return this;
  }

   /**
   * Get deviceName
   * @return deviceName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDeviceName() {
    return deviceName;
  }

  public void setDeviceName(String deviceName) {
    this.deviceName = deviceName;
  }

  public Device platformVersion(String platformVersion) {
    this.platformVersion = platformVersion;
    return this;
  }

   /**
   * Get platformVersion
   * @return platformVersion
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPlatformVersion() {
    return platformVersion;
  }

  public void setPlatformVersion(String platformVersion) {
    this.platformVersion = platformVersion;
  }

  public Device reserveKey(String reserveKey) {
    this.reserveKey = reserveKey;
    return this;
  }

   /**
   * Get reserveKey
   * @return reserveKey
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getReserveKey() {
    return reserveKey;
  }

  public void setReserveKey(String reserveKey) {
    this.reserveKey = reserveKey;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Device device = (Device) o;
    return Objects.equals(this.id, device.id) &&
        Objects.equals(this.deviceName, device.deviceName) &&
        Objects.equals(this.platformVersion, device.platformVersion) &&
        Objects.equals(this.reserveKey, device.reserveKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, deviceName, platformVersion, reserveKey);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Device {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    deviceName: ").append(toIndentedString(deviceName)).append("\n");
    sb.append("    platformVersion: ").append(toIndentedString(platformVersion)).append("\n");
    sb.append("    reserveKey: ").append(toIndentedString(reserveKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

