//
// Device.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Device: JSONEncodable {
    /** device id */
    public var id: String?
    public var deviceName: String?
    public var platformVersion: String?
    public var reserveKey: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["_id"] = self.id
        nillableDictionary["deviceName"] = self.deviceName
        nillableDictionary["platformVersion"] = self.platformVersion
        nillableDictionary["reserveKey"] = self.reserveKey
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
