//
// JiraIssuePayload.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class JiraIssuePayload: JSONEncodable {
    public var projectKey: String?
    public var assingeeName: String?
    public var assingeeKey: String?
    public var reporterName: String?
    public var reporterKey: String?
    public var description: String?
    public var summary: String?
    public var type: String?
    public var attachements: [JiraIssuePayloadAttachements]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["projectKey"] = self.projectKey
        nillableDictionary["assingeeName"] = self.assingeeName
        nillableDictionary["assingeeKey"] = self.assingeeKey
        nillableDictionary["reporterName"] = self.reporterName
        nillableDictionary["reporterKey"] = self.reporterKey
        nillableDictionary["description"] = self.description
        nillableDictionary["summary"] = self.summary
        nillableDictionary["type"] = self.type
        nillableDictionary["attachements"] = self.attachements?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
