---
swagger: "2.0"
host: "virtserver.swaggerhub.com"
basePath: "/Izinga/Hub/1.0.0"
tags:
- name: "Testsuite"
  description: "Api to handle test suites"
schemes:
- "https"
- "http"
produces:
- "application/json"
paths:
  /v3/testsuites:
    get:
      tags:
      - "Testsuite"
      summary: "get all test suite for project"
      description: "return all test suite for given project"
      operationId: "test suites for project"
      parameters:
      - name: "projectID"
        in: "path"
        description: "project id"
        required: true
        x-exportParamName: "ProjectID"
      responses:
        200:
          description: "successful operation"
  /v3/testsuite:
    get:
      tags:
      - "Testsuite"
      summary: "get all test suite for project"
      description: "return all test suite for given project"
      operationId: "test suites for project"
      parameters:
      - name: "id"
        in: "path"
        description: "test suite id"
        required: true
        x-exportParamName: "Id"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Testsuite"
definitions:
  Testsuite:
    type: "object"
    properties:
      _id:
        type: "string"
        description: "Test suite ID"
      name:
        type: "string"
        description: "Test suite  Name"
      desc:
        type: "string"
        description: "Test suite  description"
      project:
        type: "string"
        description: "Test suite  project id"
      createdBy:
        type: "string"
        description: "User who created test suite"
      updatedBy:
        type: "string"
        description: "User who uodated test suite"
    example:
      updatedBy: "updatedBy"
      createdBy: "createdBy"
      name: "name"
      project: "project"
      _id: "_id"
      desc: "desc"
