// Models.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

protocol JSONEncodable {
    func encodeToJSON() -> AnyObject
}

public enum ErrorResponse : ErrorType {
    case Error(Int, NSData?, ErrorType)
}

public class Response<T> {
    public let statusCode: Int
    public let header: [String: String]
    public let body: T?

    public init(statusCode: Int, header: [String: String], body: T?) {
        self.statusCode = statusCode
        self.header = header
        self.body = body
    }

    public convenience init(response: NSHTTPURLResponse, body: T?) {
        let rawHeader = response.allHeaderFields
        var header = [String:String]()
        for case let (key, value) as (String, String) in rawHeader {
            header[key] = value
        }
        self.init(statusCode: response.statusCode, header: header, body: body)
    }
}

private var once = dispatch_once_t()
class Decoders {
    static private var decoders = Dictionary<String, ((AnyObject) -> AnyObject)>()

    static func addDecoder<T>(clazz clazz: T.Type, decoder: ((AnyObject) -> T)) {
        let key = "\(T.self)"
        decoders[key] = { decoder($0) as! AnyObject }
    }

    static func decode<T>(clazz clazz: [T].Type, source: AnyObject) -> [T] {
        let array = source as! [AnyObject]
        return array.map { Decoders.decode(clazz: T.self, source: $0) }
    }

    static func decode<T, Key: Hashable>(clazz clazz: [Key:T].Type, source: AnyObject) -> [Key:T] {
        let sourceDictionary = source as! [Key: AnyObject]
        var dictionary = [Key:T]()
        for (key, value) in sourceDictionary {
            dictionary[key] = Decoders.decode(clazz: T.self, source: value)
        }
        return dictionary
    }

    static func decode<T>(clazz clazz: T.Type, source: AnyObject) -> T {
        initialize()
        if T.self is Int32.Type && source is NSNumber {
            return source.intValue as! T;
        }
        if T.self is Int64.Type && source is NSNumber {
            return source.longLongValue as! T;
        }
        if T.self is NSUUID.Type && source is String {
            return NSUUID(UUIDString: source as! String) as! T
        }
        if source is T {
            return source as! T
        }
        if T.self is NSData.Type && source is String {
            return NSData(base64EncodedString: source as! String, options: NSDataBase64DecodingOptions()) as! T
        }

        let key = "\(T.self)"
        if let decoder = decoders[key] {
           return decoder(source) as! T
        } else {
            fatalError("Source \(source) is not convertible to type \(clazz): Maybe swagger file is insufficient")
        }
    }

    static func decodeOptional<T>(clazz clazz: T.Type, source: AnyObject?) -> T? {
        if source is NSNull {
            return nil
        }
        return source.map { (source: AnyObject) -> T in
            Decoders.decode(clazz: clazz, source: source)
        }
    }

    static func decodeOptional<T>(clazz clazz: [T].Type, source: AnyObject?) -> [T]? {
        if source is NSNull {
            return nil
        }
        return source.map { (someSource: AnyObject) -> [T] in
            Decoders.decode(clazz: clazz, source: someSource)
        }
    }

    static func decodeOptional<T, Key: Hashable>(clazz clazz: [Key:T].Type, source: AnyObject?) -> [Key:T]? {
        if source is NSNull {
            return nil
        }
        return source.map { (someSource: AnyObject) -> [Key:T] in
            Decoders.decode(clazz: clazz, source: someSource)
        }
    }

    static private func initialize() {
        dispatch_once(&once) {
            let formatters = [
                "yyyy-MM-dd",
                "yyyy-MM-dd'T'HH:mm:ssZZZZZ",
                "yyyy-MM-dd'T'HH:mm:ss.SSSZZZZZ",
                "yyyy-MM-dd'T'HH:mm:ss'Z'",
                "yyyy-MM-dd'T'HH:mm:ss.SSS"
            ].map { (format: String) -> NSDateFormatter in
                let formatter = NSDateFormatter()
                formatter.locale = NSLocale(localeIdentifier:"en_US_POSIX")
                formatter.dateFormat = format
                return formatter
            }
            // Decoder for NSDate
            Decoders.addDecoder(clazz: NSDate.self) { (source: AnyObject) -> NSDate in
               if let sourceString = source as? String {
                    for formatter in formatters {
                        if let date = formatter.dateFromString(sourceString) {
                            return date
                        }
                    }

                }
                if let sourceInt = source as? Int {
                    // treat as a java date
                    return NSDate(timeIntervalSince1970: Double(sourceInt / 1000) )
                }
                fatalError("formatter failed to parse \(source)")
            }

            // Decoder for ISOFullDate
            Decoders.addDecoder(clazz: ISOFullDate.self, decoder: { (source: AnyObject) -> ISOFullDate in
                if let string = source as? String,
                   let isoDate = ISOFullDate.from(string: string) {
                    return isoDate
                }
                fatalError("formatter failed to parse \(source)")
            }) 

            // Decoder for [Device]
            Decoders.addDecoder(clazz: [Device].self) { (source: AnyObject) -> [Device] in
                return Decoders.decode(clazz: [Device].self, source: source)
            }
            // Decoder for Device
            Decoders.addDecoder(clazz: Device.self) { (source: AnyObject) -> Device in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = Device()
                instance.id = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["_id"])
                instance.deviceName = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["deviceName"])
                instance.platformVersion = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["platformVersion"])
                instance.reserveKey = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["reserveKey"])
                return instance
            }


            // Decoder for [Device1]
            Decoders.addDecoder(clazz: [Device1].self) { (source: AnyObject) -> [Device1] in
                return Decoders.decode(clazz: [Device1].self, source: source)
            }
            // Decoder for Device1
            Decoders.addDecoder(clazz: Device1.self) { (source: AnyObject) -> Device1 in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = Device1()
                instance.id = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["_id"])
                return instance
            }


            // Decoder for [Device2]
            Decoders.addDecoder(clazz: [Device2].self) { (source: AnyObject) -> [Device2] in
                return Decoders.decode(clazz: [Device2].self, source: source)
            }
            // Decoder for Device2
            Decoders.addDecoder(clazz: Device2.self) { (source: AnyObject) -> Device2 in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = Device2()
                instance.id = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["_id"])
                return instance
            }


            // Decoder for [Device3]
            Decoders.addDecoder(clazz: [Device3].self) { (source: AnyObject) -> [Device3] in
                return Decoders.decode(clazz: [Device3].self, source: source)
            }
            // Decoder for Device3
            Decoders.addDecoder(clazz: Device3.self) { (source: AnyObject) -> Device3 in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = Device3()
                instance.id = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["_id"])
                return instance
            }


            // Decoder for [Device4]
            Decoders.addDecoder(clazz: [Device4].self) { (source: AnyObject) -> [Device4] in
                return Decoders.decode(clazz: [Device4].self, source: source)
            }
            // Decoder for Device4
            Decoders.addDecoder(clazz: Device4.self) { (source: AnyObject) -> Device4 in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = Device4()
                instance.id = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["_id"])
                instance.command = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["command"])
                return instance
            }


            // Decoder for [Device5]
            Decoders.addDecoder(clazz: [Device5].self) { (source: AnyObject) -> [Device5] in
                return Decoders.decode(clazz: [Device5].self, source: source)
            }
            // Decoder for Device5
            Decoders.addDecoder(clazz: Device5.self) { (source: AnyObject) -> Device5 in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = Device5()
                instance.id = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["_id"])
                instance.command = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["command"])
                return instance
            }


            // Decoder for [Error]
            Decoders.addDecoder(clazz: [Error].self) { (source: AnyObject) -> [Error] in
                return Decoders.decode(clazz: [Error].self, source: source)
            }
            // Decoder for Error
            Decoders.addDecoder(clazz: Error.self) { (source: AnyObject) -> Error in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = Error()
                instance.code = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["code"])
                instance.msg = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["msg"])
                instance.fields = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["fields"])
                return instance
            }


            // Decoder for [HubDevices]
            Decoders.addDecoder(clazz: [HubDevices].self) { (source: AnyObject) -> [HubDevices] in
                return Decoders.decode(clazz: [HubDevices].self, source: source)
            }
            // Decoder for HubDevices
            Decoders.addDecoder(clazz: HubDevices.self) { (source: AnyObject) -> HubDevices in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = HubDevices()
                return instance
            }


            // Decoder for [HubSession]
            Decoders.addDecoder(clazz: [HubSession].self) { (source: AnyObject) -> [HubSession] in
                return Decoders.decode(clazz: [HubSession].self, source: source)
            }
            // Decoder for HubSession
            Decoders.addDecoder(clazz: HubSession.self) { (source: AnyObject) -> HubSession in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = HubSession()
                instance.userName = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["userName"])
                instance.projectName = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["projectName"])
                instance.userEmail = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["userEmail"])
                instance.type = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["type"])
                instance.appName = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["appName"])
                return instance
            }


            // Decoder for [InlineResponse200]
            Decoders.addDecoder(clazz: [InlineResponse200].self) { (source: AnyObject) -> [InlineResponse200] in
                return Decoders.decode(clazz: [InlineResponse200].self, source: source)
            }
            // Decoder for InlineResponse200
            Decoders.addDecoder(clazz: InlineResponse200.self) { (source: AnyObject) -> InlineResponse200 in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = InlineResponse200()
                instance.status = Decoders.decodeOptional(clazz: Bool.self, source: sourceDictionary["status"])
                instance.msg = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["msg"])
                return instance
            }


            // Decoder for [InlineResponse2001]
            Decoders.addDecoder(clazz: [InlineResponse2001].self) { (source: AnyObject) -> [InlineResponse2001] in
                return Decoders.decode(clazz: [InlineResponse2001].self, source: source)
            }
            // Decoder for InlineResponse2001
            Decoders.addDecoder(clazz: InlineResponse2001.self) { (source: AnyObject) -> InlineResponse2001 in
                let sourceDictionary = source as! [NSObject:AnyObject]
                let instance = InlineResponse2001()
                instance.status = Decoders.decodeOptional(clazz: Bool.self, source: sourceDictionary["status"])
                instance.msg = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["msg"])
                return instance
            }
        }
    }
}
