openapi: 3.0.0
info:
  title: RobusTest Api
  description: RobusTest Api documentation
  x-logo:
    url: "https://izinga.github.io/api/logo.png"
    backgroundColor: "#FFFFFF"
    altText: "RobusTest"
  version: 0.1.9
servers:
  - url: http://devicelab.robustest.com
    description: api documentation server

basePath: /v3


securityDefinitions:
  accesskey:
    type: apiKey
    name: accesskey
    in: query

security:
  - accesskey: [] 
tags:
  - name: job
    description: Job methods provide access to job
  - name: setting
    description: Store methods provide access to setting.
paths:
  /jobs/{projectID}:
    get:
      summary: List all job
      operationId: listJobs
      tags:
        - job
      parameters:
        - name: projectID
          in: path
          required: true
          description: The id of the project for which we need to list job
          schema:
            type: string
        - name: count
          in: query
          description: How many items to return at one time
          required: false
          schema:
            type: number
        - name: cursor
          in: query
          description: cursor 
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A paged array of jobs
          content:
           application/json; charset=utf-8:
             schema:
              type: object
              required:
               - cursor
               - jobs
               - totalCount
              properties:
                cursor:
                  type: string
                totalCount:
                  type: number
                jobs: 
                  type: array
                  items:
                   $ref: "components/job.yaml#/Job"


  /job/{jobID}:
    get:
      summary: Info for a specific job
      operationId: getJobByID
      tags:
        - job
      parameters:
        - name: jobID
          in: path
          required: true
          description: The id of the job to retrieve
          schema:
            type: string
      responses:
        '200':
          description: job
          content:
            application/json:

              schema:
                $ref: "components/job.yaml#/Job"


  /job/{jobID}/runs:
    get:
      summary: Get all runs for given job 
      operationId: getRunsJobByID
      tags:
        - job
      parameters:
        - name: jobID
          in: path
          required: true
          description: The id of the job to retrieve
          schema:
            type: string
      responses:
        '200':
          description: list of runs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "components/run.yaml#/Run"

  /job/{jobID}/instances:
    get:
      summary: Get all instances for given job 
      operationId: getInstancesJobByID
      tags:
        - job
      parameters:
        - name: jobID
          in: path
          required: true
          description: The id of the job to retrieve
          schema:
            type: string
      responses:
        '200':
          description: list of instances
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "components/instance.yaml#/Instance"

  /job/{jobID}/testcases:
    get:
      summary: Get all testcases for given job 
      operationId: gettTestcasesJobByID
      tags:
        - job
      parameters:
        - name: jobID
          in: path
          required: true
          description: The id of the job to retrieve
          schema:
            type: string
      responses:
        '200':
          description: list of testcases
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "components/testcase.yaml#/Testcase"

  /testcase/{testcaseID}:
    get:
      summary: Info for a specific testcase
      operationId: gettTestcaseByID
      tags:
        - job
      parameters:
        - name: testcaseID
          in: path
          required: true
          description: The id of the testcase to retrieve
          schema:
            type: string
      responses:
        '200':
          description: testcase
          content:
            application/json:
              schema:
                $ref: "components/testcase.yaml#/Testcase"

  /testcase/{testcaseID}/results:
    get:
      summary: Get all results for given testcase 
      operationId: gettResultByTestcaseID
      tags:
        - job
      parameters:
        - name: testcaseID
          in: path
          required: true
          description: The id of the testcase to retrieve
          schema:
            type: string
      responses:
        '200':
          description: list of results
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "components/result.yaml#/Result"


  /result/{resultID}:
    get:
      summary: Info for a specific result
      operationId: gettResultByID
      tags:
        - job
      parameters:
        - name: resultID
          in: path
          required: true
          description: The id of the result to retrieve
          schema:
            type: string
      responses:
        '200':
          description: result
          content:
            application/json:
              schema:
                $ref: "components/result.yaml#/Result"


  /log/{resultID}/result:
    get:
      summary: get test framework log for specific result
      operationId: gettFrameworlLogByResultID
      tags:
        - job
      parameters:
        - name: resultID
          in: path
          required: true
          description: The id of the result 
          schema:
            type: string
      responses:
        '200':
          description: log
          content:
            application/json:
              schema:
                $ref: "components/log.yaml#/Log"

  /log/{resultID}/device:
    get:
      summary: get test device log for specific result
      operationId: gettDeviceLogByResultID
      tags:
        - job
      parameters:
        - name: resultID
          in: path
          required: true
          description: The id of the result 
          schema:
            type: string
      responses:
        '200':
          description: log
          content:
            application/json:
              schema:
                $ref: "components/log.yaml#/Log"


components:
  securitySchemes:
    accesskey:
      type: apiKey
      name: accesskey
      in: query



