openapi: 3.0.0
info:
  title: RobusTest Api
  description: RobusTest Api documentation
  version: 0.1.9
servers:
  - url: http://devicelab.robustest.com
    description: api documentation server

basePath: /v3


securityDefinitions:
  accesskey:
    type: apiKey
    name: accesskey
    in: query

security:
  - accesskey: [] 
tags:
  - name: job
    description: Job methods provide access to job
  - name: setting
    description: Store methods provide access to setting.
paths:
  /jobs/{projectID}:
    get:
      summary: List all job
      operationId: listJobs
      tags:
        - job
      parameters:
        - name: projectID
          in: path
          required: true
          description: The id of the project for which we need to list job
          schema:
            type: string
        - name: count
          in: query
          description: How many items to return at one time
          required: false
          schema:
            type: number
        - name: cursor
          in: query
          description: cursor 
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A paged array of jobs
          content:
           application/json; charset=utf-8:
             schema:
              type: object
              required:
               - cursor
               - jobs
               - totalCount
              properties:
                cursor:
                  type: string
                totalCount:
                  type: number
                jobs: 
                  type: array
                  items:
                   $ref: "components/job.yaml#/Job"


  /job/{jobID}:
    get:
      summary: Info for a specific job
      operationId: getJobByID
      tags:
        - job
      parameters:
        - name: jobID
          in: path
          required: true
          description: The id of the job to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:

              schema:
                $ref: "components/job.yaml#/Job"


  /job/{jobID}/runs:
    get:
      summary: Get all run for given job 
      operationId: getRunsJobByID
      tags:
        - job
      parameters:
        - name: jobID
          in: path
          required: true
          description: The id of the job to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "components/run.yaml#/Run"


components:
  securitySchemes:
    accesskey:
      type: apiKey
      name: accesskey
      in: query



