swagger: '3.0'
title: RobusTest Api documentation 
description: RobusTest Api documentation
termsOfService: http://robustest.com/terms/
contact:
  name: API Support
  url: http://www.robustest.com/support
  email: support@robustest.com
license:
  name: Apache 2.0
  url: http://www.apache.org/licenses/LICENSE-2.0.html
version: 1.0.1

tags:
- name: Testsuite
  description : Api to handle test suites

# host: mobile.robustest.com:8085
# schemes:
#   - http
#   - https
produces:
  - application/json
# basePath: /v2
paths:
  /v3/testsuites:
    get:
      description: return all test suite for given project
      summary: get all test suite for project
      operationId: test suites for project
      tags:
      - Testsuite
      responses:
        200:
          description: successful operation
          items:
            $ref: '#/definitions/Testsuite'
      parameters:
        - name: projectID
          in: path
          description: project id
          required: true
          schema:
            type: string
            style: simple

  /v3/testsuite:
    get:
      description: return all test suite for given project
      summary: get all test suite for project
      operationId: test suites for project
      tags:
      - Testsuite
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Testsuite'
      parameters:
        - name: id
          in: path
          description: test suite id
          required: true
          schema:
            type: string
            style: simple

 
definitions:
  Testsuite:
    type : object
    properties:
      _id:
        type: string
        description: Test suite ID
      name:
        type: string
        description:  Test suite  Name
      desc:
        type: string
        description:  Test suite  description
      project:
        type: string
        description:  Test suite  project id
      testscripts:
        description:  test script id
        items:
            type: string  
      createdBy:
        type: string
        description:  User who created test suite 
      updatedBy:
        type: string
        description:  User who uodated test suite 




# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /Izinga/Hub/1.0.0
schemes:
 - https
 - http
