swagger: '3.0'
title: RobusTest Api documentation 
description: RobusTest Api documentation
termsOfService: http://robustest.com/terms/
contact:
  name: API Support
  url: http://www.robustest.com/support
  email: support@robustest.com
license:
  name: Apache 2.0
  url: http://www.apache.org/licenses/LICENSE-2.0.html
version: 1.0.1

tags:
- name: Testsuite
  description : Api to handle test suites

# host: mobile.robustest.com:8085
# schemes:
#   - http
#   - https
produces:
  - application/json
# basePath: /v2
paths:
  /admin/v3/bug/config/jira:
    post:
      description: create a jira config
      summary: create a jira config
      operationId: jira config for bug id
      tags:
      - JIRA
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/JiraConfigPayload'
      responses:
        200:
          description: successful operation
          items:
            $ref: '#/definitions/JiraConfigResponse'

definitions:
  JiraConfigPayload:
    type : object
    required: 
      - "url"
      - "name"
      - "user"
      - "password"
    properties: 
      url: 
        type: "string"
      name: 
        type: "string"
      user: 
        type: "string"
      password: 
        type: "string"

  JiraConfigResponse:
    type : array
    items:
      type: string




# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /Izinga/Hub/1.0.0
schemes:
 - https
 - http
