/**
 * RobusTest Api
 * RobusTest Apis
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RobusTestApi);
  }
}(this, function(expect, RobusTestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RobusTestApi.ProjectUpdatePayload();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProjectUpdatePayload', function() {
    it('should create an instance of ProjectUpdatePayload', function() {
      // uncomment below and update the code to test ProjectUpdatePayload
      //var instane = new RobusTestApi.ProjectUpdatePayload();
      //expect(instance).to.be.a(RobusTestApi.ProjectUpdatePayload);
    });

    it('should have the property active (base name: "active")', function() {
      // uncomment below and update the code to test the property active
      //var instane = new RobusTestApi.ProjectUpdatePayload();
      //expect(instance).to.be();
    });

    it('should have the property bugProject (base name: "bugProject")', function() {
      // uncomment below and update the code to test the property bugProject
      //var instane = new RobusTestApi.ProjectUpdatePayload();
      //expect(instance).to.be();
    });

    it('should have the property users (base name: "users")', function() {
      // uncomment below and update the code to test the property users
      //var instane = new RobusTestApi.ProjectUpdatePayload();
      //expect(instance).to.be();
    });

    it('should have the property admin (base name: "admin")', function() {
      // uncomment below and update the code to test the property admin
      //var instane = new RobusTestApi.ProjectUpdatePayload();
      //expect(instance).to.be();
    });

  });

}));
